### PR TITLE
Added two-phase ex w/ read-in config

### PR DESCRIPTION
**Pull request by AminDoost**
Added an example of two cell types, where one can also read the initial completely mixed configuration.

### CODE REVIEW

**Comment by rhomu** [comment]
Hey @AminDoost thanks for the MR! You seem to have committed some of the result files (in the data directory) that should not be here. Could I ask you to remove these files? The easiest way is to type:
```
git checkout AD
git reset --soft HEAD~1
```
And then recommit your changes without the result file.

**Comment by AminDoost** [comment]
Done. Thanks.

Amin

**Comment by rhomu** [comment]
Thanks for making the changes. Could you also remove the `.DStore` files? You can see the diff (between your branch and master) here:  https://github.com/rhomu/celadro/pull/13/files that should help you to see what you have committed.

Also: reading your config files requires a modification of the input code that you have not committed and in the curent state your runcards can not be run. Could you commit the code? I will review it when it is there.

**Comment by rhomu** [comment]
@AminDoost are you still planning on adding the changes?

**Comment by AminDoost** [comment]
I am. It's been just so busy recently, but thanks for reminding.

Amin

**Comment by rhomu** [comment]
Cool no worries, just wanted to double check! :-)

**Pull request closed without merging**
