### PR TITLE
guanming's modification

### PR DESCRIPTION
**Pull request by guanming2718**
The code is based on a previous version of celadro.  In that version, the cell division is implemented and multi-phase cells is allowed by separating the config.dat and cell.dat. Here are some modifications 
1 Change forces on center of mass into force density 
2 Add more polarisation dynamics(shape1,shape2 and contact inhibition of locomotion CIL)
3 Add more configurations
4 Add another type of walls(hard or nonadhesive)
5 Modify some methods in plot.py which allows more function such as plotting trajectories of each cell centre, plotting force densities. 
*more details are in the note.txt file(examples are in example-guanming folder). I am sorry I am not good at CUDA programming, the .cu files are untouched. I appreciate it if you could review the code. Sorry if some of the code is not easy to read or is implemented in a stupid way due to my limited coding skill.

### CODE REVIEW

**Comment by rhomu** [comment]
Hi Guanming, thanks for the pull request. Could you remove the code that you did put in `example-guanming` or either if you think these are good examples put (some) of them in the main example directory?

**Comment by guanming2718** [comment]
Dear Romain,

   Thank you for your email. I do this because some of the example is new and may not be compatible to the old examples. I am sorry I am not very familiar with git. I wonder how can I do this, does it mean I need to delete the example-guanming folder and do the pull request again? Thank you.

Best wishes
Guanming
________________________________

**Comment by rhomu** [comment]
Hey, Guanming no problem happy to help. Because this is a public repository, I'd like to keep things clean and have only examples that work and that are meaningful. So that would be great if you could think about which of your examples would be interesting to give to people that would use the code for the first time, and keep the other examples on your machine only.

The way you can achieve this with git is by removing the files using the command `git rm your-files` and then commit the result using `git commit`.

Thank you.

**Comment by rhomu** [comment]
Hey @guanming2718 ! Are you still planning on making the changes we talked about just above?

**Comment by guanming2718** [comment]
Hi Romain,
  Sorry, I made a stupid mistake. I forgot to push after I remove the folder. I think this time the folder is removed. Sorry for the inconvenience.

Best
Guanming
________________________________

**Pull request closed without merging**
